apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-team-role
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
      - daemonsets
      - services
      - deployments
      - replicasets
      - statefulsets
      - horizontalpodautoscalers
      - ingresses
      - jobs
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-team-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-team-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-team-role
subjects:
  - kind: ServiceAccount
    name: dev-team-sa
    namespace: kube-system
